### ISSUE TITLE
getting started and general goals

### ISSUE THREAD

**Issue by jonschlinkert** [less/less-docs#1]
- [x] port existing docs from lesscss.org over to use [assemble](http://assemble.io)
- [x] build system: Grunt.js, clean, jshint, assemble, assemble-less for starters
- [x] add site scaffold
- [ ] start updating with new documentation that has already been created
- [x] sync up docs with wiki
- [x] remove wiki pages and put a link to the site. It will be easier to maintain everything in one place, and it will help keep traffic from the community directed to the site.
- [ ] update theme

**Comment by SomMeri** [comment]
I am closing this since one of two remaining points is done: 
* documentation is kept (more or less)

I am not sure about theme change, but I assume we are fine with it since the issue was commented on last time two years ago.
