### ISSUE TITLE
Add CHANGELOG to website

### ISSUE THREAD

**Issue by jonschlinkert** [less/less-docs#11]
(Most of these suggestions are based on https://github.com/less/less-docs/issues/1 from @ChrisCinelli)
- [ ] add CHANGELOG to website 
- [ ] Move release update from the top to a new section called "Changelog". Possibly at the end of the page. The focus of the content of the site should always be related to the most current version. All mention of other versions should be in the changelog or "release history" section.
- [ ] Bonus: put for each version number in changelog a link to the documentation of that version. Unfortunately https://github.com/cloudhead/lesscss.org does not have tag for different version but I think they could be retrieved with a little work. From now on I would tag the new versions of the page.

**Comment by SomMeri** [comment]
Closing this since [change log](https://github.com/less/less.js/blob/master/CHANGELOG.md) is kept now .
