### ISSUE TITLE
Better contribution documentation

### ISSUE THREAD

**Issue by Soviut** [less/less-docs#14]
I've wanted to contribute to LESS plenty of times but while I'm a good programmer with a strong understanding of CSS, it isn't easy to digest a compiler.

I propose updated documentation that explains how to dive into different parts of the project. How to add functions, new syntax, fix bugs, etc.

The process is somewhat documented already but the page will soon be out of date as make is replaced with grunt builds. A clear set of instructions for setting up an environment, and clear entry points for common tasks are the only way contribution from anyone but the most dedicated will happen.

**Comment by SomMeri** [comment]
I am closing this since lesscss.org now has [developers section](http://lesscss.org/usage/#developing-less) which contains most of these suggestions.
