### ISSUE TITLE
styleguide for docs

### ISSUE THREAD

**Issue by jonschlinkert** [less/less-docs#15]
Just to get this started:

## Markdown

* Use GitHub Flavored Markdown 
* For code examples, use fenced code blocks with language definitions, versus indentation
* Use hashes for headings (`###`), not dashes 

**Resources**

* [Markdown Cheatsheet](http://assemble.io/docs/Cheatsheet-Markdown.html)
* http://github.github.com/github-flavored-markdown/

## LESS code examples

* All code in examples is indented by 2 spaces
* Always spaces, never tabs
* Always end lines with a semicolon
* One property per line
* Add a space after colons, do this `color: #900`, not this `color:#900`

**Resources**
* https://github.com/twbs/bootstrap/blob/3.0.0-wip/CONTRIBUTING.md

**Comment by seven-phases-max** [comment]
Closing since this in the main readme now: https://github.com/less/less-docs#contributing.
