### ISSUE TITLE
inconsitent use of case

### ISSUE THREAD

**Issue by MatthewBonner** [less/less-docs#247]
You should stick to a naming convention, and the one I would advise is separating words using a dash which is the standard in CSS.

For instance, on the following page:
http://lesscss.org/features/

@nice-blue is correctly typed

.screencolor should be .screen-color

and @mySelector should be @my-selector

**Comment by seven-phases-max** [comment]
Fixed in https://github.com/less/less-docs/commit/e7cde66edd5ff91d0b2e071506fb2a44e14099e6 and other commits.
