### ISSUE TITLE
Update needed for variables.md

### ISSUE THREAD

**Issue by matthew-dean** [less/less-docs#289]
Note that in https://github.com/less/less-docs/blob/master/content/features/variables.md, this is no longer correct (in ```@import``` interpolation):

> Note that currently, only variables which have been declared in the root or current scope will be considered and that only the current file and calling files will be considered when looking for a variable. This means that this usage is typically limited to when you inject a variable into the compile process or define a variable at the beginning of your root file.

> When you are importing a css file and not using the inline option (e.g. the import statement will be kept intact) then the above does not apply.

According to the latest tests in https://github.com/less/less.js/blob/master/test/less/import-interpolation.less, this is now fixed, but I'm not sure which release it made it into.

I just did a local test and I defined a variable within one import, and interpolated it to import an import from yet another import, and everything worked swimmingly. So it seems to me that both of those paragraphs can be removed, but I'm not sure if we want to say at what version this behavior changed.

**Comment by seven-phases-max** [comment]
This has been improved with [2.0.0-b2](https://github.com/less/less.js/blob/master/CHANGELOG.md#200-b2) (for the docs it's just `2.0.0` then).

**Comment by seven-phases-max** [comment]
Closing as updated with #292.
