### ISSUE TITLE
lessc -M option not working since 2.3.0

### ISSUE THREAD

**Issue by idealeric** [less/less-docs#294]
If I have a less file all.less with @import statements in it as such

```@import "dependency.less";```

This command
```$ lessc -M all.less all.css```
outputs the following:
```all.css: ```

I would expect:
```all.css: dependency.less```

I tried to browse the diff since 2.2.0 but nothing stood out as immediately obvious, but I didn't look too hard.

**Comment by lukeapage** [comment]
wrong repo..

But I fixed it (https://github.com/less/less.js/commit/66fe6d8064c29b2fbe78f4118a85bb96f859a4c6)

Will release a patch release v.soon
