### ISSUE TITLE
Cannot assemble docs in Windows

### ISSUE THREAD

**Issue by gaurav21r** [less/less-docs#297]
Hi, I've tried running the documentation generator in Windows CMD, git-bash as well as cygwin, but they all give me the same results.

```bash
$ grunt assemble
Running "assemble:site" (assemble) task
Assembling _less.github.io/about/index.html Assembling _less.github.io/about/index.html ERROR
Warning: Cannot set property 'cache' of undefined Use --force to continue.

Aborted due to warnings.
```

@jonschlinkert I really like assemble.io's concept and I wanted to use this template for a new Programming Language I created. I've tried the boilerplate-site as well but its also failing on some modifications. In any case, the LESS documentation has a very good structure.

Please HELP!!!

**Comment by lukeapage** [comment]
It worked for me in git bash a week ago after npm installing and running
grunt.

**Comment by gaurav21r** [comment]
@lukeapage I have tried deleting `node_modules` and running `npm install` several times but to no avail. Any idea about troubleshooting with the error message? Where is this `cache` variable being accessed?

**Comment by lukeapage** [comment]
Sorry no idea, sometimes assemble breaks and i debug but its been good for
a long time.

**Comment by jonschlinkert** [comment]
I'll take a look, thanks

**Comment by jonschlinkert** [comment]
@gaurav21r do you have problems running grunt tasks in general?

**Comment by gaurav21r** [comment]
@jonschlinkert No, not at all, I've run `watch` with livereload, less, custom grunt plugins, command line etc. I've also `npm install`ed `less-docs` to get the most compatible version of grunt. I'm on Win7 but I've tried cygwin as well. Assemble's `boilerplat-site` works but `boilerplate-bootstrap` and `'less-docs` don't.

Can you point me to where this `cache` variable is there?

**Comment by jonschlinkert** [comment]
ok, good to know. 

> Can you point me to where this cache variable is there?

I'm trying to remember that, but I can't think of what would cause that in assemble 0.4.x. we haven't changed anything with that version in a while, so it must be a dep

**Comment by lukeapage** [comment]
I'm on window and I tried deleting my node_modules and doing a new `npm install` - then `grunt` and it worked fine.
try doing the same or seeing if node/npm needs updating, thats all I can think of.

**Comment by gaurav21r** [comment]
@jonschlinkert @lukeapage I've treid `assembl`ing on a new Win 8 System and a Linux System and it works fine! So must be a configuration / version issue on my machine. Any debugging data / log data you suggest to help other people with this problem?

**Comment by jonschlinkert** [comment]
Really not sure, I've not been able to reproduce the issue. I'm fine with leaving this open for a bit to see if anyone else has the problem though. I'd love to figure out what's causing it if it's an assemble issue.

**Comment by gaurav21r** [comment]
:+1:

**Comment by SomMeri** [comment]
I had the same problem. It was magically solved when I run `npm install` second time. I made no other changes between runs.

**Comment by seven-phases-max** [comment]
So I'm closing this as things seem to work less or more fine with clean repo installation. (Well, the dependencies are quite tricky so some gaps here and there are expected sometimes).
