### ISSUE TITLE
Rendering Very Slow in FireFox

### ISSUE THREAD

**Issue by simonferndriger** [less/less-docs#311]
The new version 2.3.1 (also still in 2.4.0) in client mode renders normally fast in Chrome, but very slow in Firefox.

This causes LESS not being rendered on `document.ready` which produces a LOT of complications in calculating width/height/visibility/etc.

Can you please fix that?

**Comment by seven-phases-max** [comment]
See less/less.js/issues/2339.

**Comment by seven-phases-max** [comment]
Closing as "wrong repo".
