### ISSUE TITLE
Add the possibility to @import less files using an absolute path

### ISSUE THREAD

**Issue by neulandmedienagentur** [less/less-docs#316]
Add the possibility to @import less files using an absolute path.

**Comment by seven-phases-max** [comment]
Absolute paths should work fine in current Less version. If you have a particular example that does not work please report it at https://github.com/less/less.js/issues.

**Comment by seven-phases-max** [comment]
Closing as wrong repo.

**Comment by neulandmedienagentur** [comment]
I try to import a less file in my style.css file.

That works:
@import "../../../file/file/lessfile";

That doesent work:
@import "http://example.com/file/file/lessfile";

**Comment by seven-phases-max** [comment]
Yet again, this repository is for Less documentation. For Less language and compiler issues, please use https://github.com/less/less.js.
