### ISSUE TITLE
JLessC - yet another Java based port

### ISSUE THREAD

**Issue by gamma** [less/less-docs#321]
Hey Team,

our company created a performance driven port of the less compiler for Java: [JLessC][jlessc] - https://github.com/i-net-software/jlessc - mainly to get a bootstrap variant compiled as quickly as possible. Our tests - and the integration into one of our products - show that it is the fastest less port for Java to date (but does not support any scripting extensions).

It is to be said, that we're still in development though a v1.0 has been released.
It would be nice if you could consider adding us to your list of Java ports.

Thanks,
i-net software.

[jlessc]: https://github.com/i-net-software/jlessc "JLessC"

**Comment by seven-phases-max** [comment]
Thanks. Added with https://github.com/less/less-docs/commit/0bac5e610fe30c30c67c4da14c61cca3547403f4.

**Comment by codler** [comment]
+1
