### ISSUE TITLE
Spase between "selector" and ":hover"

### ISSUE THREAD

**Issue by deni35** [less/less-docs#325]
When I wrote in my .less:
.test {
    padding: 10px;
    background-color: red;

    :hover {
        background-color: blue;
    }
}

I get the next css:
.test {
  padding: 10px;
  background-color: red;
}
.test :hover {
  background-color: blue;
}
Attention on space after .test. 
It makes effect non-working. Or it makes strange behavior in shadow dom (not effect on padding border).

**Comment by seven-phases-max** [comment]
Please use [backticks](https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks) to format your code.

Additionally notice that this issue tracker is for Less Documentation development. For a "How-To" (or a sort of) questions please consider using [SO](http://stackoverflow.com/questions/tagged/less). 

---

Either way, regarding your question, see [Nested rules](http://lesscss.org/features/#features-overview-feature-nested-rules) example, and [Parent Selectors](http://lesscss.org/features/#parent-selectors-feature) for more details. E.g.:
```less
.test {
    color: red;

    &:hover {
        color: blue;
    }
}
```

**Comment by seven-phases-max** [comment]
Closing as not an issue.
