### ISSUE TITLE
Remove "Command-line With Rhino" section

### ISSUE THREAD

**Issue by SlimerDude** [less/less-docs#326]
Given that less 2.x does not ship with a Rhino version, and indeed can not even compile a Rhino specific version (see less/less.js#2316 ) it seems folly and misleading to mention it in the docs.

**Comment by cmsimike** [comment]
Agreed

**Comment by thatcher** [comment]
The docs still seem to imply support for compiling with rhino...

**Comment by seven-phases-max** [comment]
Closing per https://github.com/less/less-docs/commit/5e40fbc5c8dff7c1a65743629ff4154f98191377.
