### ISSUE TITLE
Please tag versions in documentation updates

### ISSUE THREAD

**Issue by bendavis78** [less/less-docs#333]
It's pretty much impossible for me to find documentation for older versions of less. The website has no way to view older versions, and this repository has no tags. I now have to go through and find the commit based on the date from the tag from the main project, which is kind of a pain.

**Comment by seven-phases-max** [comment]
Well, the current documentation is meant for all versions. For most new feature the corresponding section states the version the feature was introduced. Assuming there were no major breaking changes this should be enough for you to use the only docs version with either Less version.
(The documentation is maintained almost independently of Less itself, e.g. sometimes a new feature is almost instantly documented, sometimes some else feature is documented 4-5 five years later, and so on and vice-versa - so there can be no "Less version" <-> "Docs version" connection anyway).

---

Well, I can miss something of course... Could you please provide some example of a particular problem you faced?

**Comment by lukeapage** [comment]
Yep,  it would be incomplete if we tagged.  I agree we should document version introduced rather than version the site. 

The changelog is very thorough too.
