### ISSUE TITLE
[TRIVIAL] Section about screen() has incorrect holder.js images

### ISSUE THREAD

**Issue by cerlestes** [less/less-docs#334]
The section ```Function Reference > Color Blending Functions > screen()``` contains two incorrect holder.js images at the very end. They both show #999999, but should be #00ff00 and #0000ff respectively.

![Example Image](http://i.imgur.com/DPdHzCk.png)

**Comment by seven-phases-max** [comment]
Thnaks!. Fixed in https://github.com/less/less-docs/commit/80a245c04b80e1ce3586754a0d4a6bf838000df6#diff-a918874bb570c349e8ce22e9416a58d6.
```
