### ISSUE TITLE
Request: CSS Guards - When Not

### ISSUE THREAD

**Issue by Ashbo** [less/less-docs#336]
Hi,

I'd like to request that a feature is added where you can use the "not" keyword in a CSS guard. For example, in my job, we use LESS to build our websites. We do a lot of franchise work so each franchise has a variable such as:

```css
@franchise-name: foo;
```

We build websites with 15-20 franchises, sometimes more. I came across this today. I wanted to apply something along the lines of

```css
& when not (@franchise-name = foo) {
    //Button styles
}
//Button styles to apply when @franchise-name = foo
```

However I've had to do a & when statement below the original CSS, meaning there's unnecessary compiling happening.

It's hard to explain it however it's something which will not only come in handy for us as a company, but it will become very useful for a handful of other LESS users.

I'm very keen to see this sort of feature introduced as it would come in very very useful!

**Comment by seven-phases-max** [comment]
Hmm, and what http://lesscss.org/features/#mixin-guards-feature-guard-logical-operators? I.e. `not` is alredy there for a while.

**Comment by Ashbo** [comment]
I saw that but didn't didn't see one using the & operator, so I thought perhaps you couldn't. Could I use the & symbol with the not statement and it would work? I did try but to no avail, so perhaps I was doing it wrong.

Would the below work?

```css
& when not (@franchise-name = foo){
    //CSS
}
```

**Comment by seven-phases-max** [comment]
Sorry, the issue tracker is not a forum for asking generic "How-To"/"Will-This-Work?" questions of Less. If you're unsure about some snippet just test it with either online compiler (either way your codepen answers you question perfectly so please re-read the compiled result there). For a generic Less language questions consider to use [SO](http://stackoverflow.com/questions/tagged/less).

This issue tracker is for Less documentation site bug reports and development. For Less *language*  bug/issue reports and feature-requests please use [less/less.js](https://github.com/less/less.js).

**Comment by seven-phases-max** [comment]
Closing as wrong repo (and not a Less issue but already implemented feature anyway).

**Comment by Ashbo** [comment]
Hi @seven-phases-max. 

My initial feature request is still unanswered so I can't see why this is closed? I requested being able to use the ampersand (&) with a when not, which you currently can't, you can only use when not with mixins.

To simplify it... I can do:

```css
.mixin (@b) when not (@b > 0) { ... }
```

But I cannot do

```css
& when not (@variable = value) { ... }
```
