### ISSUE TITLE
Modularized-normalize-less example in Mixin Libraries

### ISSUE THREAD

**Issue by segundofdez** [less/less-docs#338]
I recently made ​​this less library https://github.com/segundofdez/normalize.less based on famous normalize.css 
The idea comes from here https://github.com/necolas/normalize.css/issues/222 and I wondered if it would be interesting include in Mixin libraries documentation as a example (before to submit a pull request).
Thanks!

**Comment by seven-phases-max** [comment]
I guess it's perfectly fine to put it there.

**Comment by segundofdez** [comment]
Thanks @seven-phases-max for your quick reply
Added a pull requests https://github.com/less/less-docs/pull/339

**Comment by seven-phases-max** [comment]
Done.
