### ISSUE TITLE
Object.create: argument is not an Object and is not null

### ISSUE THREAD

**Issue by wintersylf** [less/less-docs#341]
I'm using v2.5.0 right off the CDN and am getting the aforementioned error at line 2440:

```
if (typeof Object.create === 'undefined') {
    var F = function () {};
    F.prototype = Error.prototype;
    LessError.prototype = new F();
} else {
    LessError.prototype = Object.create(Error.prototype); # breaks here
}
```

what's going on here?

**Comment by lukeapage** [comment]
Maybe the global Error was overwritten by another script.  Can you
console.log Error and Error.prototype? What browser?

You should have reported this on the less.js repo - this is for docs
issues. less could have been safe and tested for Error.prototype before
using it (though its a bit scary if something is overriding).

**Comment by wintersylf** [comment]
thank you lukeapage, that was it.  one of my own scripts was setting Error to something, wiping out the original object.  lesson learned: beware of your variable names!
