### ISSUE TITLE
mistake in Color Blending Functions on http://lesscss.org/functions/

### ISSUE THREAD

**Issue by sultangaleev** [less/less-docs#344]
There is a mistake on lesscss.org in Function reference > Color Blending Functions > screen.

Last two examples of usage of this function

    screen(#ff6600, #00ff00);
    screen(#ff6600, #0000ff);

show gray color (#99999) as second parameter instead of green and blue respectively.

**Comment by seven-phases-max** [comment]
Thanks. It's already fixed in https://github.com/less/less-docs/commit/80a245c04b80e1ce3586754a0d4a6bf838000df6 (we just did not update site for a while, sorry).

**Comment by seven-phases-max** [comment]
Closing as fixed in https://github.com/less/less-docs/commit/80a245c04b80e1ce3586754a0d4a6bf838000df6.
