### ISSUE TITLE
Remove deprecated compiler options (or at least mark those as such).

### ISSUE THREAD

**Issue by seven-phases-max** [less/less-docs#349]
I.e.: `--compress`, `--line-numbers` etc.

**Comment by matthew-dean** [comment]
If they don't actually do anything, they aren't just deprecated, they're removed. "Deprecated" generally means they still work for now but will be removed at some point.

**Comment by seven-phases-max** [comment]
`compress` still works but it's broken by now (with no way to be fixed):
* incompatible with certain recent CSS properties where `0` and `0someunit` are different values
* breaking sourcemaps etc.
So yes, it is to be removed eventually.

**Comment by seven-phases-max** [comment]
Done (both v2 and v3 versions).
