### ISSUE TITLE
How often are the docs pushed to production / when was the last push?

### ISSUE THREAD

**Issue by dandv** [less/less-docs#355]
I wanted to fix the Clean CSS link at http://lesscss.org/#using-less-command-line-usage but I see in the repo that it has been fixed already. For  docs site, it might be nice to push changes more often, so volunteers don't go chasing issues that have already been fixed.

**Comment by seven-phases-max** [comment]
Well, Less team members are also exactly the same kind of volunteers so it's not always possible to have things going too often.

**Comment by matthew-dean** [comment]
It would be good to have a Product Lead for each repo, though. Would that be @jonschlinkert for docs?

**Comment by jonschlinkert** [comment]
I'm probably not as familiar with the docs source as @lukeapage and @seven-phases-max. that said, soon we'll be wrapping up a huge release for assemble, and if everyone's okay with it - when that happens I'd love to upgrade the build stuff for the docs. I won't change folder structure or site details of any kind - just try to get parity with what's there using the newer version of assemble. let me know if that's okay. I think that might be a step towards making the docs easier for anyone to maintain.

**Comment by matthew-dean** [comment]
@jonschlinkert I think that's fine to update Assemble since that's already what's generating it now, yes?

**Comment by jonschlinkert** [comment]
yeah, but the API is quite different - it's more like express/gulp than grunt.

**Comment by lukeapage** [comment]
I usually update when i do a release, but I haven't done a release in a
while. anyone can release,  you just need to build and check into the repo.
I will do it now...

**Comment by lukeapage** [comment]
done.
