### ISSUE TITLE
Less-preview is unable to use 2.5.2

### ISSUE THREAD

**Issue by SomMeri** [less/less-docs#368]

**Comment by lukeapage** [comment]
I need to run something and publish again...

**Comment by SomMeri** [comment]
You mean right after "Usage" on the top?

**Comment by lukeapage** [comment]
> You mean right after "Usage" on the top?

think this is the wrong issue, but yes.. one day.

as for the less-preview versions, I fixed and published. I need to spend some time tidying the (less-preview) repo though.
