### ISSUE TITLE
lessphp fatal error: parse error: failed at `-webkit-@{property}: @value;` 

### ISSUE THREAD

**Issue by soni08singh** [less/less-docs#390]
hi i go this error when i add .less in my wordpress theme - lessphp fatal error: parse error: failed at `-webkit-@{property}: @value;` wp-content/themes/theme0004/less/_mixins.less on line 4
and my mixin file code is 
// prefix declarations
.prefixed(@property, @value) {
  & when (@webkit = true) {
    -webkit-@{property}: @value;
  }

  & when (@moz = true) {
      -moz-@{property}: @value;
  }

  & when (@ms = true) {
      -ms-@{property}: @value;
  }

  & when (@o = true) {
      -o-@{property}: @value;
  }

  @{property}: @value;
}

// prefix keyframes
.keyframes(@name; @content) {
  & when (@webkit = true) {
    @-webkit-keyframes @name {
      @content();
    }
  }

  & when (@moz = true) {
      @-moz-keyframes @name {
          @content();
      }
  }

  & when (@ms = true) {
      @-ms-keyframes @name {
          @content();
      }
  }

  & when (@o = true) {
      @-o-keyframes @name {
          @content();
      }
  }

  @keyframes @name {
    @content();
  }
}
plz help me

**Comment by seven-phases-max** [comment]
(Please use [backticks](https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks) to format your code).

This issue trackers is for Less documentation. 
For Less language/compiler issue and bug reports use https://github.com/less/less.js
For `lessphp` implementation bug and issue reports use https://github.com/leafo/lessphp

Also note that GitHub trackers usually are not supposed to work as support forums, thus for "How-To", "Ho-Do-I" and "Help Me"-like questions consider to use [SO](http://stackoverflow.com/questions/tagged/less).

**Comment by seven-phases-max** [comment]
Closing as wrong repo.
