### ISSUE TITLE
Error in description

### ISSUE THREAD

**Issue by SomMeri** [less/less-docs#399]
Originally filled here: https://github.com/less/less.js/issues/2838 by @kent1ukr

http://lesscss.org/features/#features-overview-feature-functions  -> 2nd paragraph -> "that is lightened by 25% and **spun** by 8 degrees:"

**Comment by seven-phases-max** [comment]
But isn't `spun` (Past Particle)  correct? or should it be `span` instead?

**Comment by Synchro** [comment]
Yep, "spun" is correct in this context.

@kent1ukr if you're going to post issues like that, it would help if you said what you thought it should be.
