### ISSUE TITLE
dynamic classes

### ISSUE THREAD

**Issue by pakman198** [less/less-docs#403]
Hello
I was wondering if i can make something like
```
.bg-{color} {
 background-color: color
}
```
The thing is that i dont want to create a selector for each color i am using on my styles (in this case, 10).
How could i make a mixin or function to accomplish this?

Thanks in advance!

**Comment by seven-phases-max** [comment]
Please note the issue tracker is not a support forum or a Q&A facility. For general Less "How-To" questions consider suing [SO](http://stackoverflow.com/questions/tagged/less), [Gitter](https://gitter.im/less/less.js) etc.

For your question, there're a lot of ways, e.g. [[1]](http://stackoverflow.com/a/34867089/2712740), [[2]](http://stackoverflow.com/a/26435364/2712740) etc.

**Comment by seven-phases-max** [comment]
Closing as not an issue.
