### ISSUE TITLE
compiler is not working with nodejs 6.0

### ISSUE THREAD

**Issue by maxrd2** [less/less-docs#410]
I'm running arch linux.
After upgrade to nodejs 6.0, lessc doesn't produce any output files nor gives any errors..
It seems it just doesn't do anything without any error output.
EDIT: using nodejs-lessc 2.6.1-1

**Comment by seven-phases-max** [comment]
This is repository of the Less documentation/site. For Less language and compiler issues/bug reports please use https://github.com/less/less.js.

Either way see [#2881](https://github.com/less/less.js/issues/2881).

**Comment by seven-phases-max** [comment]
Closing as wrong repo.
