### ISSUE TITLE
`@plugin` directive is not documented

### ISSUE THREAD

**Issue by AndyOGo** [less/less-docs#416]
[Less version 2.5](https://github.com/less/less.js/blob/master/CHANGELOG.md#250) introduced the `@plugin` directive, but it is not documented anywhere.

**Comment by matthew-dean** [comment]
It's been on my todo list since then. Contributions always welcome!

**Comment by AndyOGo** [comment]
I see.
I would like to help. But I could only tell what you told me in the other issue.

IMHO this should include much more than just this. Like `less.tree`, `context` property of `this`, how to access less `@variables` of the current scope inside less and stuff like that.

**Comment by matthew-dean** [comment]
I'm maintaining a list of 3.0 changes here: https://github.com/less/less-meta/issues/20

The list itself may change a bit, but should be pretty close. It would be great if you want to try out different uses for `@plugin` and give some feedback.

**Comment by matthew-dean** [comment]
I've been testing `@plugin` changes with a fairly advanced use case, mostly just to see if there were any pieces missing. For instance, I wanted to see if I could add visitors from an inline plugin, which revealed that the plugin visitor code needed to be re-written.

Here's a sample of the code I've used so far in my testing: https://gist.github.com/matthew-dean/708f180b9de7a79e2349b07d58dfafe5

**Comment by matthew-dean** [comment]
Documented now.
