### ISSUE TITLE
How to enable inline javascript in browser ?

### ISSUE THREAD

**Issue by ghost** [less/less-docs#418]
Everything is in the title : 
I have 
`SyntaxError: Inline JavaScript is not enabled. Is it set in your options?`

When using Mixins libs and have no idea how to enable it in the browser…

Thanks

have a good day

T.

**Comment by matthew-dean** [comment]
See: http://lesscss.org/usage/#using-less-in-the-browser-setting-options (the javascriptEnabled option which is aliased as inlineJavascript in 3.0).

Inline JavaScript is disabled by default in Less 3.0, if you're using the developmental build.
