### ISSUE TITLE
Creating sourceMap issue on less.render

### ISSUE THREAD

**Issue by jonathanhotono** [less/less-docs#423]
Referring to issue #282 

I tried to render the less file with an aim to also get the sourceMap.
![image](https://cloud.githubusercontent.com/assets/6864547/19790508/891a7e90-9d04-11e6-8e7e-485657c81bdc.png)
The code that I used was exactly the same as in explanation but I always got an error thrown TypeError: a.getSourceMapGenerator is not a function at the cdn cloudflare. Is there any insights over this issue?

Thanks

Jonathan

**Comment by seven-phases-max** [comment]
Wrong repository. For Less language and compiler issues use https://github.com/less/less.js.

---
(Either way a quick answer: browser version of the Less compiler do not include sourcemap generation facility (this would increase the size of the script too much for the sake of usually unused stuff). For a debugging purposes consider using more convenient client-side tools (e.g. `node` etc.)).

**Comment by seven-phases-max** [comment]
Closing as wrong repo.
