### ISSUE TITLE
Option to use less js in browser without compiling on load

### ISSUE THREAD

**Issue by rejhgadellaa** [less/less-docs#424]
Hi there,

I was wondering if it's possible to have an option for the 'live' js version of less that stops it from compiling less stylesheets automatically?

I'm asking because I precompiled a bunch of configurations (dark, light, etc) but want to give the user the option to have more control. I figured I could do that using something like `less.modifyVars({'@base-color':'#hexhex'});` and render it on the fly. But when I include lessjs it automatically compiles everything as soon as the js file finishes loading and that isn't really very optimal (I know, I'm complaining about optimal and thinking about doing client side compiling but at least that's on the user's request so he can expect it to take a second)

Anyway, would love a feature like that and couldn't find anything in the docs about it so I figured I could give it a shot and propose it :)

**Comment by matthew-dean** [comment]
Feature requests should go in the https://github.com/less/less.js repo.
