### ISSUE TITLE
Adobe Dreamweaver CC now supports Less preprocessing

### ISSUE THREAD

**Issue by kgalle** [less/less-docs#425]
Hi,

I work at Adobe as a product marketing manager for Dreamweaver CC. Dreamweaver has recently been completely re-imagined for designers who code. We are excited to announce that this latest version of Dreamweaver CC includes built-in support for Less. I would like to update the editors and plugins page https://github.com/less/less-docs/blob/master/content/usage/editors-and-plugins.md

On that page, I would like to add the phrase _(built-in support)_ next to the word Dreamweaver. If you would prefer, I can make the pull request, commit the change, and push. Please feel free to reach out to me with any questions.

Best,

Kyle

**Comment by seven-phases-max** [comment]
Done with https://github.com/less/less-docs/commit/1fafea195f811fff0d123f1c3dd17a08ebf8a4ab.

**Comment by kgalle** [comment]
Thank you! Do you have an idea of when this change will go live on the github and lesscss.org sites?

**Comment by seven-phases-max** [comment]
>Do you have an idea of when this change will go live on the github and lesscss.org sites?

No idea, sorry (usually the live site is updated when a new release is out). Technically, anyone can submit a PR with the live site update anytime (never happend before though).

**Comment by kgalle** [comment]
Thank you for letting me know. I will let the community drive that PR when it deems it is necessary.
