### ISSUE TITLE
Side navigation "jumps" on scroll

### ISSUE THREAD

**Issue by matthew-dean** [less/less-docs#427]
![687474703a2f2f692e696d6775722e636f6d2f796464745276662e676966](https://cloud.githubusercontent.com/assets/414752/21152596/d1d0d626-c11b-11e6-9ae9-c0a489006fe4.gif)

Reported by @candh 
> * CHROME Version 54.0.2840.98 (64-bit)
> * MAC OS SIERRA 10.12.1 (Macbook Air, non-retina)
> * I'M USING A TRACKPAD.

**Comment by candh** [comment]
hating ass

**Comment by su-narthur** [comment]
Same on Chrome 55, Sierra 10.12.1, iMac (Retina 5K, 27-inch, Late 2014), using Magic Trackpad.

**Comment by matthew-dean** [comment]
I think this is fixed in the new 3.x docs, yes?

**Comment by su-narthur** [comment]
Yeah, seems better.

**Comment by matthew-dean** [comment]
Okay, closing, thanks @su-narthur.
