### ISSUE TITLE
New feature to mixin

### ISSUE THREAD

**Issue by mastermehdi** [less/less-docs#436]
Can we add a new feature to mixin for supporting this state?

.test() { color: white; } .test() { color: red; } body { .test() }

Compiled to:
a { color: white; color: red; }

But desired compile is:
a { color: red; }

**Comment by seven-phases-max** [comment]
This is a repository for the Less documentation. 

For Less language issue reports and feature requests use https://github.com/less/less.js/issues. Before creating a new ticket please review https://github.com/less/less.js/blob/3.x/CONTRIBUTING.md.

**Comment by seven-phases-max** [comment]
Closing as "wrong repo".
