### ISSUE TITLE
Document Local Variable Scoping in Import Files

### ISSUE THREAD

**Issue by BerkeleyTrue** [less/less-docs#437]
Took me a while to figure this out and it would help others if it was explicitly documented.

```less
&{ import "./foo.less" }
```
Prevents variables in foo.less from overwriting variables globally.

**Comment by seven-phases-max** [comment]
I'm afraid the documentation just can't house all the zillion little tips and tricks out there. If it does so the noise will  sepulcher the actual reference info. So the stuff like this is more like a content for a book instead.

**Comment by seven-phases-max** [comment]
Closing

**Comment by BerkeleyTrue** [comment]
Local scoping in css is becoming quite popular. I was surprised to find this was not a built in feature of the language and having to dig around issues to get this bit of information seemed nonsensical when it could be added to the documentation quite easily.

**Comment by seven-phases-max** [comment]
The need for the detailed `scope` reference section is evident (this section then should obviously mention the ability of the anonymouse ruleset, i.e. `& {...}`, to isolate whatever code from an outer scope). But then it has to be something more than just one quite specific example. So I'm just rewording the closing reason.

>this was not a built in feature of the language

What language, Less? But the unique scope of a ruleset *is* its native feature (same native is the thing that the '& {...}` is nothing but an ordinary just unnamed ruleset, thus following  all scoping rules).

> it could be added to the documentation quite easily.

Ready to make a PR? (The first question from me is: what section exactly could could land in? '&', 'import', 'namespaces', 'variables scope'? By now I don't think any of them fits).

**Comment by BerkeleyTrue** [comment]
> this was not a built in feature of the language

By this I meant some explicit syntax. Just by looking at `&{ import "./foo.less" }` it isn't immediately apparent what this is doing or how I could search for this in documentation. I've documented it in our codebase in a comment but not everywhere I am using it. This could cause confusion to our future contributors, many of whom are new developers and unfamiliar with less. 

If there was something like `import scoped 'foo.less'` or `import anon 'foo.less'`  I could understand quite easily or search for `less css import scoped` and the answer would probably pop right up.

> it could be added to the documentation quite easily.

> Ready to make a PR?

I apologies if my previous comment came off as rude or offensive in some way. I meant no harm by it. I am of the opinion that it is best to document features that users might want to use. I don't think anyone ever complained about a language having too much documentation. I can understand that finding where to put it might be difficult but I don't think that warrants not documenting it in some official way.

My motivation for opening this issue was to prevent future `less` users from spending a ton of time (like I did) searching for how to scope import statements and instead spend their time actually writing code.

**Comment by matthew-dean** [comment]
I agree that `& { ... }` should be be documented specifically for a section about isolating scope. I don't think any new syntax is needed, just a special note about that technique.

**Comment by seven-phases-max** [comment]
>search for less css import scoped and the answer would probably pop right up.

Next time just do: http://stackoverflow.com/search?q=%5Bless%5D+scope+import.

>import scoped 'foo.less' or import anon 'foo.less'

Ah, I see now what you mean by "native" . Never mind then.
