### ISSUE TITLE
Remove -x deprecated compress option from the command-line examples

### ISSUE THREAD

**Issue by vinischeidegger** [less/less-docs#444]
Although deprecated functions should be in the documentation, they shouldn't serve as examples, if the intent is not using them anymore.

**Comment by seven-phases-max** [comment]
See #349.

**Comment by seven-phases-max** [comment]
Closing as duplicate of #349.

**Comment by arndissler** [comment]
Shouldn't this be closed?

**Comment by seven-phases-max** [comment]
@arndissler Indeed. Thanks!

**Comment by seven-phases-max** [comment]
Finally closing as implemented (`-x` examples are kicked from the docs already).
