### ISSUE TITLE
Possible to merge properties of same selector in different places?

### ISSUE THREAD

**Issue by folosophy** [less/less-docs#451]
Let's say I have the following:

```
html {
  color: red;
}

html {
  left: 4px;
}
```

This will output two of the same selectors in the final CSS file, which seems wasteful.

Is there any way to combine properties, so the CSS just prints one selector? 

```
html {
  color: red;
  left: 4px;
}
```

**Comment by seven-phases-max** [comment]
In short: no (Less is not CSS optimizer/analyzer) - you can use aggressive clean-css opts though. See also https://github.com/less/less.js/issues/930.

**Comment by seven-phases-max** [comment]
Closing as a dupicate of https://github.com/less/less.js/issues/930 (and wrong repo).
