### ISSUE TITLE
Add documentation for `if()` function

### ISSUE THREAD

**Issue by matthew-dean** [less/less-docs#457]
See: https://github.com/less/less.js/pull/3079

**Comment by seven-phases-max** [comment]
Done with https://github.com/less/less-docs/commit/dd7e30f25d058bab5e8f83a14e251627f12a3f2b.
Please feel free to fix any awkward wording, grammar, formatting you'll notice.

**Comment by matthew-dean** [comment]
Awesome! Thanks!
