### ISSUE TITLE
When writing ".less" files, the computer suddenly loses power, and then the data of  ".less" files all becomes 0, how can you recover!

### ISSUE THREAD

**Issue by GitHubLlj** [less/less-docs#458]
When writing ".less" files, the computer suddenly loses power, and then the data of  ".less" files all becomes 0000, how can you recover!
在编写Less文件的时候，电脑突然断电了，然后Less文件的数据全部变成了0000 0000，怎么样可以恢复！

[style.zip](https://github.com/less/less-docs/files/1367646/style.zip)
![tim 20171009143848](https://user-images.githubusercontent.com/30815794/31327124-948c92b6-acff-11e7-8881-a5b192efd379.png)

**Comment by matthew-dean** [comment]
Er, this is not a Less issue.
