### ISSUE TITLE
Documentation missing on globalVars, errorReporting and text/less/text/x-less

### ISSUE THREAD

**Issue by andrewwakeling** [less/less-docs#46]
The following options/functionality seems to be undocumented:
- globalVars - https://github.com/less/less.js/issues/1479
- errorReporting - https://github.com/less/less.js/issues/792 
- style tags with "text/less" or "text/x-less" - https://github.com/less/less.js/issues/104

I don't know whether any of these are deprecated (or not) but still think there should be a mention of it on lesscss.org or on the project wiki.

**Comment by reidab** [comment]
If writing these docs, it's worth noting that double-quoting is required to make LESS interpret passed variables as strings: https://github.com/less/less.js/issues/2372

**Comment by seven-phases-max** [comment]
>it's worth noting that double-quoting is required to make LESS interpret passed variables as strings: less/less.js#2372

PRs are welcome.

**Comment by seven-phases-max** [comment]
Closing as all three items are in the docs by now.
