### ISSUE TITLE
Is partial file supported in less? Can't find it in the docs.

### ISSUE THREAD

**Issue by lzl124631x** [less/less-docs#465]
Partial file are prefixed with underscore "_".

**Comment by seven-phases-max** [comment]
No. "Partials" is solely a building tools concept not a language concept. With common build-chain tools (like gulp, grunt etc.) you may set whatever file/dir mask for the files to compile.

**Comment by seven-phases-max** [comment]
Closing as not an docs issue (Docs can't and should not cover every silly kludges developed for other tools/languages).
