### ISSUE TITLE
Add cli at package.json not working

### ISSUE THREAD

**Issue by QuietWind** [less/less-docs#473]
scene 1: "prebuild": "lessc ./assets/index.less ./assets/index.css",

scene 2:  "prebuild": "lessc ./assets/index.less ./index.css",

above package.json two cmd，scene 2 is working, and scene 1 not working!

**Comment by seven-phases-max** [comment]
Note this is the repository for the Less documentation. For Less language/compiler issue/bug reports use [less.js/issues](https://github.com/less/less.js/issues).

**Comment by seven-phases-max** [comment]
Closing as wrong repo.
