### ISSUE TITLE
less2css error: `lessc` is not available

### ISSUE THREAD

**Issue by salamat1307** [less/less-docs#478]
when I save .less file I have got error on  confirmation modal: less2css error: `lessc` is not available. How can fix it?

**Comment by seven-phases-max** [comment]
And by `less2css` you mean what exactly? If it's about some Sublime plugin, it has nothing to do with this or https://github.com/less/less.js repositories.
Specifically, *this* is a repository for the Less language and compiler *documentation*.
(In other words we don't do any `less2css` here, and even if we would - please also note the GitHub issue tracker are not support forums. I.e. read [common GH issue-tracker guidelines](https://github.com/necolas/issue-guidelines/blob/master/CONTRIBUTING.md).)
