### ISSUE TITLE
https://lesscss.org/ certificate error

### ISSUE THREAD

**Issue by Munter** [less/less-docs#486]
Visiting https://lesscss.org/ results in a certificate error. It would be good to get this fixed and redirect all http traffic to the https equivalent

![image](https://user-images.githubusercontent.com/331790/43194788-8781f6f0-9003-11e8-87f5-d69b0e3e66d7.png)

**Comment by matthew-dean** [comment]
It was a problem in Github's certificate.

**Comment by AlexWayfer** [comment]
> It was a problem in Github's certificate.

It's still a problem. 

And this problem can be resolved: https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

**Comment by matthew-dean** [comment]
Use http://lesscss.org/

**Comment by pownas** [comment]
Please do something about the certificate error, since this is some trouble now that nearly all modern browsers only fully support HTTPS . 
Maybe switch to less.github.io , or check on an automated "let's encrypt"?

**Comment by pownas** [comment]
And I guess that you have followed the guide here: [github-pages/configuring-a-custom-domain-for-your-github-pages-site](https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/configuring-a-custom-domain-for-your-github-pages-site)
So that the custom domain are correctly setup under Github-pages?

**Comment by qJake** [comment]
How has this issue been open for over 2.5 years? ☹️ 

Looks like it's [currently hosted by 1api.net](https://whois.domaintools.com/lesscss.org). Who has control over this account? (@matthew-dean How can we find this out?)

This isn't just a problem for people visiting your site directly, **other (secure) sites that link to this insecure site may throw warnings as well.** And search engines will penalize you for not having SSL/TLS enabled. This is harming your overall reputation. You should resolve this as quickly as possible.

You just need to update the A record for the domain apex:

https://dns.google.com/query?name=lesscss.org&rr_type=A&ecs=

To instead point to these four IPs:

    185.199.108.153
    185.199.109.153
    185.199.110.153
    185.199.111.153

Make sure that [GitHub is configured to host your Apex domain.](https://docs.github.com/en/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site#configuring-an-apex-domain)

Then, go and enable this option:

![image](https://user-images.githubusercontent.com/652006/107828396-5f60fb00-6d4e-11eb-8d60-115c4ddadde8.png)

They'll issue, apply, and automatically keep up to date a Let's Encrypt certificate for the site.

Simple as that!

**Comment by matthew-dean** [comment]
@qJake Less [needs active maintainers](https://twitter.com/LessToCSS/status/1353815168581390338). If you (or anyone else), wants to step up, I'm happy to share whatever I know.

The answer is, I don't know who owns and/or controls this domain. Possibly @lukeapage, possibly @cloudhead. I haven't had / don't have the time to track down that information.

> Simple as that!

If it's simple, please make it happen!

**Comment by cloudhead** [comment]
Thanks, I've made the update to the new IPs.

**Comment by cloudhead** [comment]
Looks like https://lesscss.org/ works fine now!

**Comment by matthew-dean** [comment]
Hey thanks @cloudhead!!

**Comment by qJake** [comment]
Excellent! Thanks so much for fixing this, @cloudhead! 🙏
