### ISSUE TITLE
Poor description text

### ISSUE THREAD

**Issue by matthew-dean** [less/less-docs#5]
When pasting to LinkedIn, lesscss.org auto-generated this description text:

>Are some elements in your style sheet proportional to other elements? Operations let you add, subtract, divide and multiply property values and colors, giving you the power to create complex relationships between properties. Operations should only be performed within parentheses in order to ensure compatibility with CSS.

I recommend we clean up meta tags on the site (and add appropriate ones for Twitter cards and Facebook posts) to make the site more friendly to pasting on various social platforms.

**Comment by SomMeri** [comment]
Closing: I searched less-docs repo for the poor text, but did not found it.
