### ISSUE TITLE
multiple @media can not be defined with same css

### ISSUE THREAD

**Issue by BananaAcid** [less/less-docs#509]
I believe, this should be working:

    @media (max-device-width : 812px) and (orientation : landscape),  // till iPhoneX landscape
    @media (max-width: 630px)   // browser Portrait
    {
        // some css
    }

**Comment by matthew-dean** [comment]
No, it shouldn't. That's not a real `@media` query.

Correct code should be:

```css
@media (max-device-width : 812px) and (orientation : landscape),  // till iPhoneX landscape
(max-width: 630px)   // browser Portrait
{
    // some css
}
```
