### ISSUE TITLE
not correct behavior for grid-column/row

### ISSUE THREAD

**Issue by Serega5j** [less/less-docs#510]
Hi dear developer. In my code, I can write:
` {

		grid-column-start: 2;
		grid-column-end: 12;
		grid-row-start: 2;
		grid-row-end: 3;

} `  We can contraction it as next one

`{

		grid-column: 2 / 12;
		grid-row: 2 / 3;

}`  I expect to result in CSS 

`{

		grid-column: 2 / 12;
		grid-row: 2 / 3;

}`
Let me know if I did something wrong. Thanks.
less v2.5.1

**Comment by seven-phases-max** [comment]
See http://lesscss.org/usage/#less-options-math (for ancient versions use `strict-math=true`).
