### ISSUE TITLE
'border-radius' resolve error

### ISSUE THREAD

**Issue by tuhongwei** [less/less-docs#517]
When I set the value of  'border-radius' similar to '0 0 50% 50% / 0 0 100% 100%', it will be resolved   '0 0 50% Infinity% 0 100% 100%'

**Comment by seven-phases-max** [comment]
See [Math options](http://lesscss.org/usage/#less-options-math).

---
Note this is Less documentation repository. For Less language/compiler stuff use https://github.com/less/less.js.

**Comment by seven-phases-max** [comment]
Closing as wrong repo (and not an issue anyway).

**Comment by matthew-dean** [comment]
@seven-phases-max We should probably more strongly callout that `parens-division` should be the setting added to any Less compilation setup, as it removes these math edge cases, but isn't currently the _default_ so that it didn't automatically break things.

**Comment by seven-phases-max** [comment]
@matthew-dean Yes.
