### ISSUE TITLE
Overview -> Operatins the division example is misleading

### ISSUE THREAD

**Issue by mannixsuo** [less/less-docs#561]
It's my first time use less, I'm wondering It's powerful and simple.
First I see the example bellow
```css
@color: #224488 / 2; //results in #112244
```
Then I write like this
```css
@imageSize: 110px;
@cameraSize: @imageSize / 2 ;
```
but I got
```css
  @imageSize: 110px;
  @cameraSize: 110px / 2; // just string connectin no math division happend
```
After some research I finally know there are some Math options and requires parentheses for division. 
So I hope you can make some notice in the division example .

**Comment by iChenLei** [comment]
Thanks for your suggestion!

**Comment by Yetispapa** [comment]
This actually broke my whole code, cause I make many divisions and the compiler is now giving:

`top: 20px / 2;`

instead of

`top: 10px;`

**Comment by iChenLei** [comment]
closed by https://github.com/less/less-docs/pull/565
