### ISSUE TITLE
A plan for Chinese doc.

### ISSUE THREAD

**Issue by fuchunhui** [less/less-docs#571]
We know that the translation of Chinese documents of Less has fallen behind, and we have plans to move forward and align to the latest version of less.

At present, the latest version of Less is v4 1.2, and the corresponding Chinese document is still v3.11.1, so I want to update it.

But, where 's its repo? I need help.

**Comment by happysmile12321** [comment]
> We know that the translation of Chinese documents of Less has fallen behind, and we have plans to move forward and align to the latest version of less.
> 
> At present, the latest version of Less is v4 1.2, and the corresponding Chinese document is still v3.11.1, so I want to update it.
> 
> But, where 's its repo? I need help.

no chinese version.just english version is well.nothing so hard english in less.stop your stupid try!Thats just waste of your time.isn't it better to escape after 996 of every day?Why you plan to do such a horrible things.

**Comment by fuchunhui** [comment]
Do what you want to do, choose what you love, not what others see as right.

**Comment by KimYangOfCat** [comment]
@fuchunhui  the behind chinese docs are unofficial, if you want update them, you need to find their repositories. Unfortunately, almost all of them are not open source.
By the way, there is not official plan to support Chinese!

**Comment by fuchunhui** [comment]
@KimYangOfCat thanks.
In March this year, I talked with @iChenLei , but the follow-up was put on hold for the time being, no time both.

**Comment by KimYangOfCat** [comment]
if less team member has plan to support Chinese, we can try, and I am willing to make contribution for it

**Comment by AndyCorona** [comment]
how's going ?

**Comment by fuchunhui** [comment]
time going.
