### ISSUE TITLE
Toning down some the 'client side' language

### ISSUE THREAD

**Issue by bedney** [less/less-docs#85]
First of all, I was absolutely stunned to see the new documentation site - it is AWESOME!! Thanks to all who are contributing to this!!

I know that the current maintainers of LESS are not big fans of running LESS on the client side. But I also know there are quite a few folks out there, like myself, who are running LESS on the client side and are quite happy with that. In fact, since the perf updates in 1.6, performance has gotten quite a bit better.

Therefore, reading things like:

"We do not want to encourage client-side usage in production - this is because it adds a performance degradation for the user, who will sees a delay (even if it is sub 1 second) while LESS styles are compiled to CSS, and may cause cosmetic issues if Javascript errors occur."

is taking a pretty strident tone against running LESS on the client.

Let me offer the following verbiage, and feel free to throw sticks, tomatoes and rocks at me :-).

"While it is possible to use LESS on the client side in production, please be aware that there are performance implications for doing so (although the latest releases of LESS are quite a bit faster). Also, sometimes cosmetic issues can occur if a JavaScript error occurs. This is a trade off of flexibility vs. speed. For the fastest performance possible for a static web site, we recommend compiling LESS on the server side".

Thoughts?

Cheers,

- Bill

**Comment by lukeapage** [comment]
Async xhr request is becoming deprecated meaning eventually sites will show
unstyled then flash to the styled content.
