### ISSUE TITLE
rename this repo?

### ISSUE THREAD

**Issue by jonschlinkert** [less/less-docs#89]
@lukeapage I didn't think about this until now, but we probably should have just renamed this repo to less.github.io so the activity etc. would be retained, and we could use master for source files and gh-pages for the live site.  we could still do this during a slow-ish time of day. so basically delete the other repo, then rename this one.  should only take a few minutes I think. Thoughts?

**Comment by seven-phases-max** [comment]
Repo names and the site are now in the state they are supposed to be (I guess so?) so closing this.
